// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuasY-vzblGd_We3a7AyJzXpz0uXuIrCo',
    appId: '1:557547174269:web:902ba554a6e1c714657414',
    messagingSenderId: '557547174269',
    projectId: 'stock-flutter-app-c4bcd',
    authDomain: 'stock-flutter-app-c4bcd.firebaseapp.com',
    storageBucket: 'stock-flutter-app-c4bcd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvs2rzSR49NeJI2v97Yna2NwBgj5p5YZ0',
    appId: '1:557547174269:android:24fb4b12c084565a657414',
    messagingSenderId: '557547174269',
    projectId: 'stock-flutter-app-c4bcd',
    storageBucket: 'stock-flutter-app-c4bcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvA0hF8J1gdBpje9aJNgGrgqURDiqQmQA',
    appId: '1:557547174269:ios:fb913cdb529a2519657414',
    messagingSenderId: '557547174269',
    projectId: 'stock-flutter-app-c4bcd',
    storageBucket: 'stock-flutter-app-c4bcd.firebasestorage.app',
    iosBundleId: 'com.example.stockFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvA0hF8J1gdBpje9aJNgGrgqURDiqQmQA',
    appId: '1:557547174269:ios:fb913cdb529a2519657414',
    messagingSenderId: '557547174269',
    projectId: 'stock-flutter-app-c4bcd',
    storageBucket: 'stock-flutter-app-c4bcd.firebasestorage.app',
    iosBundleId: 'com.example.stockFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuasY-vzblGd_We3a7AyJzXpz0uXuIrCo',
    appId: '1:557547174269:web:b08f39f98cc57588657414',
    messagingSenderId: '557547174269',
    projectId: 'stock-flutter-app-c4bcd',
    authDomain: 'stock-flutter-app-c4bcd.firebaseapp.com',
    storageBucket: 'stock-flutter-app-c4bcd.firebasestorage.app',
  );
}
